/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokensSol from "./ERC20Tokens.sol";
export type { erc20TokensSol };
import type * as ercTokensSol from "./ERCTokens.sol";
export type { ercTokensSol };
export type { AMM } from "./AMM";
